spring:
  profiles:
    active: local

app:
  ranking:
    min-votes: 5

  cache:
    ttl-days: 30
    expired-days: 60

    discography-ttl-days: 7
    discography-expired-days: 14


resilience4j:
  circuitbreaker:
    instances:
      geniusApi:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s